config/routes.rb
RedditRails::Application.routes.draw do
  devise_for :users
  resources  :pages
  resources  :links
  resources  :comments
  resources  :votes
  root :to =>"pages#index"

  get 'search' => 'search#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many   :comments
  has_many   :votes
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :links
  has_many :comments
  has_many :votes 
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  validates  :user_id, :uniqueness => { :scope => :link_id}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :authenticate_user!

  def create
   @comment = current_user.comments.create(post_params)
   redirect_to :back
  end

  private
  
  def post_params
    params.require(:comment).permit(:user_id, :link_id, :message)
  end

end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  
  def show
    @link    = Link.find(params[:id])
    @comment = Comment.new  
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new params[:link].permit(:url, :title)
    if @link.save
      flash[:success] = 'Link Created'
      redirect_to @link
    else
      render 'show'
    end  
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
   @links = Link.paginate(:page => params[:page] || 1, :per_page => params[:per_page] || 25) 
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    @links = Link.search(:title => params[:q].page(params[:page].per_page(20)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    @vote = Vote.where(:link_id => params[:vote][:link_id], :user_id => current_user.id).first
    if @vote
      @vote.up = params[:vote][:up]
      @vote.save
    else
      @vote = current_user.votes.create(post_params)
    end
    redirect_to :back
  end

  private
  
  def post_params
    params.require(:vote).permit(:user_id, :link_id, :up  )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RedditRails</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
	<link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>

<body>

	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>
	
	<div class="navbar navbar-fixed-top"
		<div class="navbar-inner">
			<div class="container">
				<a href="/" class="brand". Reddit on Rails</a>
				<div class='nav-collapse'>
					<ul class='nav'>
						<%# user is logged in, show log out link%>
						<% if current_user.present? %>
							<%= link_to 'Sign-Out', destroy_user_session_path, method: :delete %>
						<%# user is not logged in, show sign-up and sign-in links%>
						<% else %>
							<%= link_to 'Sign In', new_user_session_path %> |
							<%= link_to 'Register Now', new_user_registration_path %>
						<% end %>
					</ul>
				</div>
			</div>
		</div>		
	</div>

	<div class="container" id="getting started">
		<div class="row">
			<div class="span6 offset2">
			<div class="page-header"></div>

			#add Flash message
			<% [:notice, :error, :alert].each do |level| %>
  			<% unless flash[level].blank? %>
    			<div data-alert="alert" class="alert alert-<%= level %> fade in">
      			<a class="close" data-dismiss="alert" href="#">&times;</a>
      			<%= content_tag :p, flash[level] %>
			    </div>
			  <% end %>
			<% end %>

			<%= content_for :sidebar do %>
				<%= link_to "Add a link", new_link_path %><br />
			<% end %>

			<%= content_for :sidebar do %>
				<%= link_to "Awesome Blog", 'http://schneems.com' %>
			<% end %>
			
			<%= form_tag(search_path, :method => "get", :style => "margin: 5px 0 0 0") do %>
  		<%= text_field_tag(:q, nil, :placeholder => "search") %>
  		<%= submit_tag("Search") %>
			<% end %>	
			
				<%= yield %>
				<%= yield :sidebar %>
			</div>
		</div>
	</div>
	<%= javascript_include_tag "application" %>
</body>
</html>

app/views/links/create.html.erb
<h1>Create</h1>

<h2>Link Successfully Created</h2>

<P>Title: <%= @link.title.capitalize %></p>
<p> Url: 	<%= @link.url %> </p>

app/views/links/new.html.erb
<h1>new</h1>

<%= form_for @link do |f| %>
	<% if @link.errors.any? %>
		<div id="error_explaination">
			<h2><%= pluralize(@link.errrors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
			<% @links.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
	  <%= f.label :url %>:
	  <%= f.text_field :url %><br />
	</div>

	<div class="field">
	  <%= f.label :title %>:
	  <%= f.text_field :title %><br />
	</div>
	
	<div class="actions"> 
	  <%= f.submit %>
	</div>
<% end %>


<h2>Comments:</h2>
<% @link.comments.each do |comment| %>
  <p><%= comment.message %></p>
<% end %>

app/views/links/show.html.erb
<h1>"show"</h1>
<p> <%= link_to @link.title , @link.url %> </p>

<%= form_for @comment do |f| %>
	<% if @comment.errors.any? %>
		<div id="error_explaination">
			<h2><%= pluralize(@comment.errrors.count, "error") %> prohibited this user from being saved:</h2>

			<ul>
			<% @comment.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>
			<% end %>
			</ul>
		</div>
	<% end %>

	<div class="field">
		<%= f.hidden_field :link_id, :value => @link.id %>
	  <%= f.label :message %>:
	  <%= f.text_area :message, :placeholder => "Add a comment" %><br />
	</div>
	
	<div class="actions"> 
	  <%= f.submit %>
	</div>
<% end %>

app/views/pages/index.html.erb
<ul>
  <% @links.each do |link| %>
    <li>
    	<p><%= link_to link.title, link.url %></p>
    	<p><%= link_to "coments", link %></p>
    	<% if current_user && current_user.votes.where(:link_id => link.id, :up => true).present? %>
    		*
    	<% else %>
    	 <%= link_to "+", votes_path(:vote => {:link_id => link.id, :up => true}), :method => :post %>
    	 <%= link_to "-", votes_path(:vote => {:link_id => link.id, :up => false}), :method => :post %>
    	 <p>Votes: <%= link.votes.where(:up => true).count - link.votes.where(:up => false).count %></p>
    	<% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add a link", new_link_path %>

<p><%= will_paginate @links %></p>